# Используем официальный образ PostgreSQL в качестве базового
FROM postgres:18.6

# Устанавливаем locales
RUN apt-get update && apt-get install -y locales locales-all && rm -rf /var/lib/apt/lists/*

# Запускаем PostgreSQL с конфигом
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]