# Используем официальный образ Python
FROM python:3.14-slim

# Устанавливаем системные зависимости нужные для C-расширений
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /backend

# Устанавливаем переменную
ENV APP_ENV=production

# Копируем файл зависимостей и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальной код приложения
COPY . .

# Разрешаем выполнение скрипта
RUN chmod +x ./api-entrypoint.sh

# Указываем, какой порт должен быть открыт
EXPOSE 8000

# Запускаем приложение
ENTRYPOINT ["/backend/api-entrypoint.sh"]
