"""insert data and triggers

Revision ID: 68733a8cdb36
Revises: 8e6fc6df77f8
Create Date: 2026-09-25 11:54:41.576447

"""

import os
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68733a8cdb36"
down_revision: Union[str, Sequence[str], None] = "8e6fc6df77f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_unique_constraint(None, "products", ["sku"], schema="app_schema")
  op.drop_constraint(
    op.f("warehouse_cells_rack_number_key"), "warehouse_cells", schema="app_schema", type_="unique"
  )
  op.drop_constraint(
    op.f("warehouse_cells_shelf_number_key"), "warehouse_cells", schema="app_schema", type_="unique"
  )
  op.create_unique_constraint(
    "uq_rack_shelf", "warehouse_cells", ["rack_number", "shelf_number"], schema="app_schema"
  )

  # Читаем SQL файл с данными и выполняем его
  BASE_DIR = Path(__file__).resolve().parents[2]
  SQL_DIR = Path(BASE_DIR, "psql-configs")

  insert_path = os.path.join(SQL_DIR, "insert.sql")
  triggers_path = os.path.join(SQL_DIR, "triggers.sql")
  with open(insert_path, "r", encoding="utf-8") as f:
    sql_insert = f.read()
  with open(triggers_path, "r", encoding="utf-8") as f:
    sql_trigger = f.read()

  op.execute(sa.text(sql_insert))
  op.execute(sa.text(sql_trigger))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint("uq_rack_shelf", "warehouse_cells", schema="app_schema", type_="unique")
  op.create_unique_constraint(
    op.f("warehouse_cells_shelf_number_key"),
    "warehouse_cells",
    ["shelf_number"],
    schema="app_schema",
    postgresql_nulls_not_distinct=False,
  )
  op.create_unique_constraint(
    op.f("warehouse_cells_rack_number_key"),
    "warehouse_cells",
    ["rack_number"],
    schema="app_schema",
    postgresql_nulls_not_distinct=False,
  )
  op.drop_constraint(None, "products", schema="app_schema", type_="unique")
  # ### end Alembic commands ###
