"""delete lenght string for password_hash in users model

Revision ID: 8e6fc6df77f8
Revises: a1b561c58656
Create Date: 2026-09-24 09:31:45.363262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6fc6df77f8'
down_revision: Union[str, Sequence[str], None] = 'a1b561c58656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False,
               schema='app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='app_schema')
    # ### end Alembic commands ###
