"""add inventory_stocks

Revision ID: a1b561c58656
Revises: d6ec6603f5e3
Create Date: 2026-09-22 14:55:59.559206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b561c58656'
down_revision: Union[str, Sequence[str], None] = 'd6ec6603f5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_stocks',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('cell_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['app_schema.warehouse_cells.warehouse_cell_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['app_schema.products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'cell_id'),
    schema='app_schema'
    )
    op.add_column('products', sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False), schema='app_schema')
    op.create_unique_constraint(None, 'users', ['username'], schema='app_schema')
    op.add_column('warehouse_cells', sa.Column('current_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False), schema='app_schema')
    op.create_check_constraint('chk_current_weight_limit', 'warehouse_cells', 'current_weight_kg <= max_weight_kg', schema='app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_current_weight_limit', 'warehouse_cells', schema='app_schema', type_='check')
    op.drop_column('warehouse_cells', 'current_weight_kg', schema='app_schema')
    op.drop_constraint(None, 'users', schema='app_schema', type_='unique')
    op.drop_column('products', 'weight_kg', schema='app_schema')
    op.drop_table('inventory_stocks', schema='app_schema')
    # ### end Alembic commands ###
